name: Sync Mirror
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync from Gitea
        run: |
          git remote add upstream https://git.sheetjs.com/sheetjs/sheetjs.git
          git fetch upstream
          git checkout master
          git merge upstream/master
          git push origin master
